//
// Created by Luis Pelegrina Gutiérrez on 8/5/24.
//
#include "Includes.h"

/*
Declaration of the variables inside the tree, and information about the tree structure. Remember that the tree can be browsed by either opening a TBrowser in a root terminal or using commands in the terminal, go to https://root.cern.ch/root/htmldoc/guides/users-guide/Trees.html for more information on this.
TREE STRUCTURE:
The files produced by the analizer "run_analyzeEvents_Truth.fcl" follow the following structure:
    TFile example_name.root (This is the file that you have saved in Data)
        TDirectoryFile "ana" (This is a file inside the root_file where the trees are stored. It is automatically created by the analyzer);
            TTree "tree" (This tree contains information about simulated neutrino interactions, it has information about the neutrino, the generator particles and the g4 particles, more information ahead)
            TTree "sub_run_tree (This tree contains information about the subruns used to generate the neutrino events, more information ahead)
*/


/*
SubRun tree: Generating neutrino simulations can be very time and resource consuming. For that reason when generating large amounts of data
the generation is split among several independent simulations that are launched at the same time merged at the end. Each independent simulation is called a subrun.
For example, for generating 100k neutrino single interaction events they are tipically splitted in batches of around 100 events. This leads to the output being splitted in 1000 subruns that each produce a file with 100 events on each file.
 */

//Subrun tree variables:
double POT; // Numbers of Protons that had to be simulated colliding in SBNDs Berilium target to generate all the neutrino interactions in the subrun, Protons On Target (POT)
double spill; //Number of neutrino spills that had where simulated. This number is currently bugged and always output 0. As a general rule of thumb each spill contains around 1 or 2 neutrino interactions. For scaling the simulation to a target number of time of the BNB running is easier to use the POT.
// If you really want to use spills just remember that 1 spill is approx 5*10^12 POT
int num_gen_evts; //Number of events generated in each subrun. In this case it will always be 100 but may change if you do a preselection (remove some uninteresting events) on the analizer stage
unsigned int run_ID;// Number assigned to each run¡
unsigned int subrun_ID;// Number assigned to each subrun¡



//Event tree: As previously stated in each subrun several neutrino interaction are included. In the event tree each entry correspond to a single neutrino interaction.
//Event tree variables:
//Variables concerning general event information:
unsigned int event_ID; // Number assigned to each event, in this case it goes from 1 to 100
int gen_index; // Generator index, it should be 1 for genie, 2 for corsika and 0 for unknown

//ALL variables with name nu_* give information of the initial neutrino interaction with an argon nucleus, nucleon or quark. A definition of each variable is given but go to https://internal.dunescience.org/doxygen/classsimb_1_1MCNeutrino.html#a8e213917487f1f5cd52ca5280d33a777 or https://internal.dunescience.org/doxygen/MCNeutrino_8h_source.html to see additional documentation.
int nu_PDG; //PDG Code of the neutrino (number given to each type of particle, a document with all the PDGCodes can be found at https://pdg.lbl.gov/2020/reviews/rpp2020-rev-monte-carlo-numbering.pdf)
double nu_E0; //Energy of the neutrino before interacting
double nu_weight; //Weight given by the generator to the neutrino event, for events generated by GENIE is always 0 but it changes for other generators, as GiBUU
unsigned int nu_interaction_mode; //Interaction Mode of the neutrino, it is given as an integer. What each integer represents can be consulted in this webpage,https://internal.dunescience.org/doxygen/MCNeutrino_8h_source.html but it is also written at the end of this file. It should only be used with events generated by genie.
unsigned int nu_interaction_type; //Interaction type of the neutrino, kind of an expanded interaction mode with more information. Again what each integer represents can be consulted in this webpage,https://internal.dunescience.org/doxygen/MCNeutrino_8h_source.html but it is also written at the end of this file.
int nu_CC_NC;   //Interger that gives wether the interaction is Charged Current (CC, 0) or Neutral Current (NC, 1)
int nu_target;  //PDG of Nuclear target
int nu_HitNuc;  //PDG of interacting nucleon (2212 (proton) or 2112 (neutron))
int nu_HitQuark;  //PDG of interacting quark for Deep Inelastic Events (DIS) events only, as PDG code
double nu_W; // Hadronic invariant mass, in GeV
double nu_X;// Bjorken x=Q^2/(2M*(E_neutrino-E_lepton)), unitless
double nu_Y;// Inelasticity y=1-(E_lepton/E_neutrino), unitless
double nu_QSqr; // Momentum transfer Q^2, in GeV^2

//IMPORTANT PRO TIP!!!
// For variables that are a "std::vector" of any type for accessing then in a TTree a vector POINTER is needed, initialized either as a nullptr or as a new vector (If not the programm will crash).
// This also applies for entries of type "string". Remember to create a pointer variable add a "*" after the variable type. Example: instead of writing "int exmp_var" write "int* exmp_var = nullptr"
//IMPORTANT!!!!

//Variables containing all the information of the particles at the generator stage, before the propagation by G4. It also includes particles that are not propagated by G4 but used to generate the final state.
//All this variables are a vector, with each entry representing 1 particle.
// For example, particle number 0 has his properties given by entry 0: its Id is gen_part_trackId->at(0), its status code is gen_part_statusCode->at(0)...
//For the same reason particle 1 has its ID given by gen_part_trackId->at(1)...
std::vector<int>* gen_part_trackID = new std::vector<int>; //ID of the particle
std::vector<int>* gen_part_mother = new std::vector<int>; //ID of the mother of the given particle
std::vector<int>* gen_part_statusCode= new std::vector<int>; // Status code of the particle, it is given by an integer. The meaning of each code can be found in the genie manual https://genie-docdb.pp.rl.ac.uk/DocDB/0000/000002/003/man.pdf, in page 235 but is also included at the end of this file.
std::vector<int>* gen_part_PDGcode = new std::vector<int>; //PDG Code of the particle (number given to each type of particle, a document with all the PDGCodes can be found at https://pdg.lbl.gov/2020/reviews/rpp2020-rev-monte-carlo-numbering.pdf)
std::vector<double>* gen_part_mass = new std::vector<double>; //Mass of the particle
std::vector<double>* gen_part_E0 = new std::vector<double>; //Initial energy of the particle
std::vector<double>* gen_part_start_pos_X = new std::vector<double>;//X coordinate of the starting position of the particle
std::vector<double>* gen_part_start_pos_Y = new std::vector<double>;//Y coordinate of the starting position of the particle
std::vector<double>* gen_part_start_pos_Z = new std::vector<double>;//Z coordinate of the starting position of the particle
std::vector<double>* gen_part_P0_X = new std::vector<double>;//X coordinate of the starting momentum of the particle
std::vector<double>* gen_part_P0_Y = new std::vector<double>;//Y coordinate of the starting momentum of the particle
std::vector<double>* gen_part_P0_Z = new std::vector<double>;//Z coordinate of the starting momentum of the particle

//Variables containing all the information of the particles at the geant4 stage, after the propagation by G4.
//All this variables are a vector, with each entry representing 1 particle, as with the gen_part_*.
//Geant4 Particles variables
std::vector<int>* g4_part_trackID = new std::vector<int>;       // ID of the particle
std::vector<int>* g4_part_mother = new std::vector<int>;        // ID of the mother of the given particle
std::vector<int>* g4_part_PDGcode = new std::vector<int>;       // PDG Code of the particle (number given to each type of particle, a document with all the PDGCodes can be found at https://pdg.lbl.gov/2020/reviews/rpp2020-rev-monte-carlo-numbering.pdf)
std::vector<double>* g4_part_mass = new std::vector<double>;    // Mass of the particle
std::vector<double>* g4_part_TL = new std::vector<double>;;     // Track Length of the particle
std::vector<double>* g4_part_E0 = new std::vector<double>;      // Initial energy of the particle
std::vector<double>* g4_part_Ef = new std::vector<double>;      // inal energy of the particle
    
std::vector<double>* g4_part_start_pos_X = new std::vector<double>;   // X coordinate of the starting position of the particle
std::vector<double>* g4_part_start_pos_Y = new std::vector<double>;   // Y coordinate of the starting position of the particle
std::vector<double>* g4_part_start_pos_Z = new std::vector<double>;   // Z coordinate of the starting position of the particle
std::vector<double>* g4_part_start_T = new std::vector<double>;       // Time when the particle is created (?)
std::vector<double>* g4_part_end_pos_X = new std::vector<double>;     // X coordinate of the final position of the particle
std::vector<double>* g4_part_end_pos_Y = new std::vector<double>;     // Y coordinate of the final position of the particle
std::vector<double>* g4_part_end_pos_Z = new std::vector<double>;     // Z coordinate of the final position of the particle
std::vector<double>* g4_part_end_T = new std::vector<double>;

std::vector<double>* g4_part_P0_X = new std::vector<double>;    // X coordinate of the starting momentum of the particle
std::vector<double>* g4_part_P0_Y = new std::vector<double>;    // Y coordinate of the starting momentum of the particle
std::vector<double>* g4_part_P0_Z = new std::vector<double>;    // Z coordinate of the starting momentum of the particle
std::vector<double>* g4_part_Pf_X = new std::vector<double>;    // X coordinate of the final momentum of the particle
std::vector<double>* g4_part_Pf_Y = new std::vector<double>;    // Y coordinate of the final momentum of the particle
std::vector<double>* g4_part_Pf_Z = new std::vector<double>;    // Z coordinate of the final momentum of the particle
  
std::vector<std::string>* g4_part_process = new std::vector<string>;      // string containing the name of the process that generated the particle
std::vector<std::string>* g4_part_end_process = new std::vector<string>;  // string containing the name of the process that ended the particle


/*
In reconstruction, the process is:
// Isolate the particles that leave a track with a commom vertex. 
This is what we call a SLICE (slc): the group of energy depositions that seem that belong to the same interaction. 
Then, for each slice, we try to reconstruct the particles that belong to it and their properties. 
For example, we try to reconstruct the vertex of the interaction, the energy of the particles, their direction... 
Each particle that is identified as a track is called a PFP, and the properties of the track are reconstructed.
*/


//Slice related parameters
int slc_ID;
bool slc_is_reconstructed;

//Primary vertex parameters
double slc_prim_vtx_x, slc_prim_vtx_y, slc_prim_vtx_z;                  // Position in x, y, z of the vertex of the interaction

//Truth primary vertex parameters
double slc_true_prim_vtx_x, slc_true_prim_vtx_y, slc_true_prim_vtx_z;   // All the same, but truth values (this is, the ACTUAL value of the position of teh vertex)

//PFP parameters: RECONSTRUCTED information of the particles of the interaction
std::vector<int>* slc_pfp_ID = new std::vector<int>;          // ID of the particle in the slice
std::vector<int>* slc_pfp_parent_ID = new std::vector<int>;   // ID of the parent particle in the slice (the particle that gives rise to this one, for example a pion that decays into a muon and a neutrino would be the parent of the muon and the neutrino)
std::vector<bool>* slc_pfp_mother_is_primary = new std::vector<bool>;   // Boolean variable that inficates if its is a primary particle (true) or it comes from the decay of another particle (false)
std::vector<double>* slc_pfp_track_score = new std::vector<double>;     // Score given by the reconstruction to the particle of being a track (as opposed to a shower), between 0 and 1, with 1 being more likely to be a track and 0 more likely to be a shower
std::vector<bool>* slc_pfp_has_track = new std::vector<bool>;           // Boolean variable that indicates if the particle has a track associated to it (true) or not (false). Almost always should be true
std::vector<double>* slc_pfp_vtx_x = new std::vector<double>;           // Reconstructed vertex (x): reconstructed initial position of the particle, which should be close to the primary vertex of the interaction
std::vector<double>* slc_pfp_vtx_y = new std::vector<double>;           // Reconstructed vertex (y): reconstructed initial position of the particle, which should be close to the primary vertex of the interaction
std::vector<double>* slc_pfp_vtx_z = new std::vector<double>;            // Reconstructed vertex (z): reconstructed initial position of the particle, which should be close to the primary vertex of the interaction
std::vector<double>* slc_pfp_trk_start_x = new std::vector<double>;             // Position where a track starts (x)
std::vector<double>* slc_pfp_trk_start_y = new std::vector<double>;             // Position where a track starts (y)
std::vector<double>* slc_pfp_trk_start_z = new std::vector<double>;             // Position where a track starts (z)
std::vector<double>* slc_pfp_trk_end_x = new std::vector<double>;               // Position where a track ends (x)
std::vector<double>* slc_pfp_trk_end_y = new std::vector<double>;               // Position where a track ends (y)
std::vector<double>* slc_pfp_trk_end_z = new std::vector<double>;               // Position where a track ends (z)
std::vector<double>*  slc_pfp_track_dir_x = new std::vector<double>;            // Direction in x of the track
std::vector<double>*  slc_pfp_track_dir_y = new std::vector<double>;            // Direction in y of the track
std::vector<double>*  slc_pfp_track_dir_z = new std::vector<double>;            // Direction in z of the track
// (slc_pfp_track_dir_x, slc_pfp_track_dir_y, slc_pfp_track_dir_z) should give the normalized direction of the track
std::vector<double>*	slc_pfp_track_length = new std::vector<double>;           // Length of the track
std::vector<double>*  slc_pfp_track_kinetic_energy = new std::vector<double>;   // Kinectic energy of the particle in MeV
std::vector<double>*  slc_pfp_track_visible_energy = new std::vector<double>;   // Visible energy of the particle (should be the same as kinetic energy) in MeV
std::vector<double>*  slc_pfp_track_theta = new std::vector<double>;            // Angle of the particle with the z axis. z = direction of the neutrino
std::vector<double>*  slc_pfp_track_phi = new std::vector<double>;              // Angle of the particle with the x axis in the x-y plane

/*
IMPORTANT!!!!
kinetic_energy and visible_energy should give the same value
KINETIC ENERGY WAS BUGGED AT SOME POINT (AND I BELIEVE THAT IT IS STILL BUGGED)
IT IS SAFER TO USE VISIBLE ENERGY
*/


// Truth information from the PFP particles:
// The previous variables were the RECONSTRUCTED ones, which may differ from the actual values
// The actual values are in the following variables, which are the same as the previous ones but with "true" in their name.
std::vector<int>* slc_pfp_true_trackid = new std::vector<int>;                  // Track ID of the truth particle that gives more hits in this trace
std::vector<int>* slc_pfp_true_pdg = new std::vector<int>;                      // pdg of the truth particle that gives more hits in this trace
std::vector<double>* slc_pfp_true_energy = new std::vector<double>;             // Energy of the truth particle that gives more hits in this trace
std::vector<double>* slc_pfp_true_p_x = new std::vector<double>;                // Momenta in x of the truth particle that gives more hits in this trace
std::vector<double>* slc_pfp_true_p_y = new std::vector<double>;                // Momenta in y of the truth particle that gives more hits in this trace
std::vector<double>* slc_pfp_true_p_z = new std::vector<double>;                // Momenta in z of the truth particle that gives more hits in this trace


// Shower variables. I comment them out because I do not thik they will be nedded
/*
std::vector<double>* slc_pfp_shower_dir_x  = new std::vector<double>;          // Direction in x of a shower
std::vector<double>* slc_pfp_shower_dir_y  = new std::vector<double>;          // Direction in y of a shower
std::vector<double>* slc_pfp_shower_dir_z  = new std::vector<double>;          // Direction in z of a shower
std::vector<double>*	slc_pfp_shower_length  = new std::vector<double>;        // Length of the shower
std::vector<double>*	slc_pfp_shower_opening_angle = new std::vector<double>;  // Opening angle of the shower (how it spreads out)
std::vector<double>*	slc_pfp_shower_energy = new std::vector<double>;         // Reconstructed energy of the shower
std::vector<double>*	slc_pfp_shower_dEdx = new std::vector<double>;           // dE/dx of the shower
*/

//Function to set all the branches of the tree containing event information
void set_branch(TTree* tree) {

  tree->SetBranchAddress("event_ID", &event_ID);
  tree->SetBranchAddress("subrun_ID", &subrun_ID);
  tree->SetBranchAddress("run_ID", &run_ID);

  tree->SetBranchAddress("gen_index", &gen_index);
  tree->SetBranchAddress("nu_PDG", &nu_PDG);
  tree->SetBranchAddress("nu_E0", &nu_E0);
  tree->SetBranchAddress("nu_weight", &nu_weight);
  tree->SetBranchAddress("nu_interaction_mode", &nu_interaction_mode);
  tree->SetBranchAddress("nu_interaction_type", &nu_interaction_type);
  tree->SetBranchAddress("nu_CC_NC", &nu_CC_NC);
  tree->SetBranchAddress("nu_target", &nu_target);
  tree->SetBranchAddress("nu_HitNuc", &nu_HitNuc);
  tree->SetBranchAddress("nu_HitQuark", &nu_HitQuark);
  tree->SetBranchAddress("nu_W", &nu_W);
  tree->SetBranchAddress("nu_X", &nu_X);
  tree->SetBranchAddress("nu_Y", &nu_Y);
  tree->SetBranchAddress("nu_QSqr", &nu_QSqr);

  //MCTruth Particles variables
  tree->SetBranchAddress("gen_part_trackID", &gen_part_trackID);
  tree->SetBranchAddress("gen_part_statusCode", &gen_part_statusCode);
  tree->SetBranchAddress("gen_part_mother", &gen_part_mother);
  tree->SetBranchAddress("gen_part_PDGcode", &gen_part_PDGcode);
  tree->SetBranchAddress("gen_part_mass", &gen_part_mass);
  tree->SetBranchAddress("gen_part_E0", &gen_part_E0);
  tree->SetBranchAddress("gen_part_start_pos_X", &gen_part_start_pos_X);
  tree->SetBranchAddress("gen_part_start_pos_Y", &gen_part_start_pos_Y);
  tree->SetBranchAddress("gen_part_start_pos_Z", &gen_part_start_pos_Z);
  tree->SetBranchAddress("gen_part_P0_X", &gen_part_P0_X);
  tree->SetBranchAddress("gen_part_P0_Y", &gen_part_P0_Y);
  tree->SetBranchAddress("gen_part_P0_Z", &gen_part_P0_Z);
  
  //Geant4 Particles variables
  tree->SetBranchAddress("g4_part_trackID", &g4_part_trackID);
  tree->SetBranchAddress("g4_part_mother", &g4_part_mother);
  tree->SetBranchAddress("g4_part_PDGcode", &g4_part_PDGcode);
  tree->SetBranchAddress("g4_part_mass", &g4_part_mass);
  tree->SetBranchAddress("g4_part_TL", &g4_part_TL);
  tree->SetBranchAddress("g4_part_E0", &g4_part_E0);
  tree->SetBranchAddress("g4_part_Ef", &g4_part_Ef);

  tree->SetBranchAddress("g4_part_start_pos_X", &g4_part_start_pos_X);
  tree->SetBranchAddress("g4_part_start_pos_Y", &g4_part_start_pos_Y);
  tree->SetBranchAddress("g4_part_start_pos_Z", &g4_part_start_pos_Z);
  tree->SetBranchAddress("g4_part_start_T", &g4_part_start_T);
  tree->SetBranchAddress("g4_part_end_pos_X", &g4_part_end_pos_X);
  tree->SetBranchAddress("g4_part_end_pos_Y", &g4_part_end_pos_Y);
  tree->SetBranchAddress("g4_part_end_pos_Z", &g4_part_end_pos_Z);
  tree->SetBranchAddress("g4_part_end_T", &g4_part_end_T);

  tree->SetBranchAddress("g4_part_P0_X", &g4_part_P0_X);
  tree->SetBranchAddress("g4_part_P0_Y", &g4_part_P0_Y);
  tree->SetBranchAddress("g4_part_P0_Z", &g4_part_P0_Z);
  tree->SetBranchAddress("g4_part_Pf_X", &g4_part_Pf_X);
  tree->SetBranchAddress("g4_part_Pf_Y", &g4_part_Pf_Y);
  tree->SetBranchAddress("g4_part_Pf_Z", &g4_part_Pf_Z);

  tree->SetBranchAddress("g4_part_process", &g4_part_process);
  tree->SetBranchAddress("g4_part_end_process", &g4_part_end_process);

  tree->SetBranchAddress("slc_is_reconstructed", &slc_is_reconstructed);
  tree->SetBranchAddress("slc_ID", &slc_ID);

  tree->SetBranchAddress("slc_prim_vtx_x", &slc_prim_vtx_x);
  tree->SetBranchAddress("slc_prim_vtx_y", &slc_prim_vtx_y);
  tree->SetBranchAddress("slc_prim_vtx_z", &slc_prim_vtx_z);

  tree->SetBranchAddress("slc_true_prim_vtx_x", &slc_true_prim_vtx_x);
  tree->SetBranchAddress("slc_true_prim_vtx_y", &slc_true_prim_vtx_y);
  tree->SetBranchAddress("slc_true_prim_vtx_z", &slc_true_prim_vtx_z);

  tree->SetBranchAddress("slc_pfp_ID", &slc_pfp_ID);
  tree->SetBranchAddress("slc_pfp_parent_ID", &slc_pfp_parent_ID);
  tree->SetBranchAddress("slc_pfp_mother_is_primary", &slc_pfp_mother_is_primary);
  tree->SetBranchAddress("slc_pfp_track_score", &slc_pfp_track_score);
  tree->SetBranchAddress("slc_pfp_has_track", &slc_pfp_has_track);

  tree->SetBranchAddress("slc_pfp_vtx_x", &slc_pfp_vtx_x);
  tree->SetBranchAddress("slc_pfp_vtx_y", &slc_pfp_vtx_y);
  tree->SetBranchAddress("slc_pfp_vtx_z", &slc_pfp_vtx_z);

    tree->SetBranchAddress("slc_pfp_true_trackid", &slc_pfp_true_trackid);
    tree->SetBranchAddress("slc_pfp_true_pdg", &slc_pfp_true_pdg);
    tree->SetBranchAddress("slc_pfp_true_energy", &slc_pfp_true_energy);
    tree->SetBranchAddress("slc_pfp_true_p_x", &slc_pfp_true_p_x);
    tree->SetBranchAddress("slc_pfp_true_p_y", &slc_pfp_true_p_y);
    tree->SetBranchAddress("slc_pfp_true_p_z", &slc_pfp_true_p_z);

    tree->SetBranchAddress("slc_pfp_trk_start_x", &slc_pfp_trk_start_x);
    tree->SetBranchAddress("slc_pfp_trk_start_y", &slc_pfp_trk_start_y);
    tree->SetBranchAddress("slc_pfp_trk_start_z", &slc_pfp_trk_start_z); 
    tree->SetBranchAddress("slc_pfp_trk_end_x", &slc_pfp_trk_end_x);
    tree->SetBranchAddress("slc_pfp_trk_end_y", &slc_pfp_trk_end_y);
    tree->SetBranchAddress("slc_pfp_trk_end_z", &slc_pfp_trk_end_z);

    tree->SetBranchAddress("slc_pfp_track_dir_x", &slc_pfp_track_dir_x);
    tree->SetBranchAddress("slc_pfp_track_dir_y", &slc_pfp_track_dir_y);
    tree->SetBranchAddress("slc_pfp_track_dir_z", &slc_pfp_track_dir_z);
    tree->SetBranchAddress("slc_pfp_track_length", &slc_pfp_track_length);

    tree->SetBranchAddress("slc_pfp_track_kinetic_energy", &slc_pfp_track_kinetic_energy);
    tree->SetBranchAddress("slc_pfp_track_visible_energy", &slc_pfp_track_visible_energy);
    tree->SetBranchAddress("slc_pfp_track_theta", &slc_pfp_track_theta);
    tree->SetBranchAddress("slc_pfp_track_phi", &slc_pfp_track_phi);

    /*
    tree->SetBranchAddress("slc_pfp_shower_dir_x", &slc_pfp_shower_dir_x);
    tree->SetBranchAddress("slc_pfp_shower_dir_y", &slc_pfp_shower_dir_y);
    tree->SetBranchAddress("slc_pfp_shower_dir_z", &slc_pfp_shower_dir_z);
    tree->SetBranchAddress("slc_pfp_shower_length", &slc_pfp_shower_length);
    tree->SetBranchAddress("slc_pfp_shower_opening_angle", &slc_pfp_shower_opening_angle);
    tree->SetBranchAddress("slc_pfp_shower_energy", &slc_pfp_shower_energy);
    tree->SetBranchAddress("slc_pfp_shower_dEdx", &slc_pfp_shower_dEdx);
    */

}

//Function to set all the branches of the tree containing subrun information
void set_branch_subtree(TTree* tree) {
  tree->SetBranchAddress("POT", &POT);
  tree->SetBranchAddress("spill", &spill);
  tree->SetBranchAddress("num_gen_evts", &num_gen_evts);
  tree->SetBranchAddress("run_ID", &run_ID);
  tree->SetBranchAddress("subrun_ID", &subrun_ID);
}

/*
Neutrino interaction  mode by number:
kUnknownInteraction        =   -1
kQE                        =    0,
kRes                       =    1,
kDIS                       =    2,
kCoh                       =    3,
kCohElastic                =    4,
kElectronScattering        =    5,
kIMDAnnihilation           =    6,
kInverseBetaDecay          =    7,
kGlashowResonance          =    8,
kAMNuGamma                 =    9,
kMEC                       =   10,
kDiffractive               =   11,
kEM                        =   12,
kWeakMix                   =   13,
 */

/*
Neutrino interaction type by number:
kNuanceOffset              = 1000,                ///< offset to account for adding in Nuance codes to this enumkCCQE                      = kNuanceOffset +  1,  ///< charged current quasi-elastickNCQE                      = kNuanceOffset +  2,  ///< neutral current quasi-elastickResCCNuProtonPiPlus       = kNuanceOffset +  3,  ///< resonant charged current, nu p -> l- p pi+kResCCNuNeutronPi0         = kNuanceOffset +  4,  ///< resonant charged current, nu n -> l- p pi0
kResCCNuNeutronPiPlus      = kNuanceOffset +  5,  ///< resonant charged current, nu n -> l- n pi+
kResNCNuProtonPi0          = kNuanceOffset +  6,  ///< resonant neutral current, nu p -> nu p pi0
kResNCNuProtonPiPlus       = kNuanceOffset +  7,  ///< resonant neutral current, nu p -> nu p pi+
kResNCNuNeutronPi0         = kNuanceOffset +  8,  ///< resonant neutral current, nu n -> nu n pi0
kResNCNuNeutronPiMinus     = kNuanceOffset +  9,  ///< resonant neutral current, nu n -> nu p pi-
kResCCNuBarNeutronPiMinus  = kNuanceOffset + 10,  ///< resonant charged current, nubar n -> l+ n pi-
kResCCNuBarProtonPi0       = kNuanceOffset + 11,  ///< resonant charged current, nubar p -> l+ n pi0
kResCCNuBarProtonPiMinus   = kNuanceOffset + 12,  ///< resonant charged current, nubar p -> l+ p pi-
kResNCNuBarProtonPi0       = kNuanceOffset + 13,  ///< resonant charged current, nubar p -> nubar p pi0
kResNCNuBarProtonPiPlus    = kNuanceOffset + 14,  ///< resonant charged current, nubar p -> nubar n pi+
kResNCNuBarNeutronPi0      = kNuanceOffset + 15,  ///< resonant charged current, nubar n -> nubar n pi0
kResNCNuBarNeutronPiMinus  = kNuanceOffset + 16,  ///< resonant charged current, nubar n -> nubar p pi-
kResCCNuDeltaPlusPiPlus    = kNuanceOffset + 17,
kResCCNuDelta2PlusPiMinus  = kNuanceOffset + 21,
kResCCNuBarDelta0PiMinus   = kNuanceOffset + 28,
kResCCNuBarDeltaMinusPiPlus= kNuanceOffset + 32,
kResCCNuProtonRhoPlus      = kNuanceOffset + 39,
kResCCNuNeutronRhoPlus     = kNuanceOffset + 41,
kResCCNuBarNeutronRhoMinus = kNuanceOffset + 46,
kResCCNuBarNeutronRho0     = kNuanceOffset + 48,
kResCCNuSigmaPlusKaonPlus  = kNuanceOffset + 53,
kResCCNuSigmaPlusKaon0     = kNuanceOffset + 55,
kResCCNuBarSigmaMinusKaon0 = kNuanceOffset + 60,
kResCCNuBarSigma0Kaon0     = kNuanceOffset + 62,
kResCCNuProtonEta          = kNuanceOffset + 67,
kResCCNuBarNeutronEta      = kNuanceOffset + 70,
kResCCNuKaonPlusLambda0    = kNuanceOffset + 73,
kResCCNuBarKaon0Lambda0    = kNuanceOffset + 76,
kResCCNuProtonPiPlusPiMinus= kNuanceOffset + 79,
kResCCNuProtonPi0Pi0       = kNuanceOffset + 80,
kResCCNuBarNeutronPiPlusPiMinus = kNuanceOffset + 85,
kResCCNuBarNeutronPi0Pi0   = kNuanceOffset + 86,
kResCCNuBarProtonPi0Pi0    = kNuanceOffset + 90,
kCCDIS                     = kNuanceOffset + 91,  ///< charged current deep inelastic scatter
kNCDIS                     = kNuanceOffset + 92,  ///< charged current deep inelastic scatter
kUnUsed1                   = kNuanceOffset + 93,
kUnUsed2                   = kNuanceOffset + 94,
kCCQEHyperon               = kNuanceOffset + 95,
kNCCOH                     = kNuanceOffset + 96,
kCCCOH                     = kNuanceOffset + 97,  ///< charged current coherent pion
kNuElectronElastic         = kNuanceOffset + 98,  ///< neutrino electron elastic scatter
kInverseMuDecay            = kNuanceOffset + 99,  ///< inverse muon decay
kMEC2p2h                   = kNuanceOffset + 100  ///< extension of nuance encoding for MEC / 2p2h

 */

/*
 Status code of the particles:
Undefined: kIStUndefined -1
Initial state: kIStInitialState 0
Stable final state: kIstStableFinalState 1
Intermediate state: kIStIntermediateState 2
Decayed state: kIStDecayedState 3
Nucleon target: kIStNucleonTarget 11
DIS pre-fragm. hadronic state: kIStDISPreFragmHadronicState 12
Resonant pre-decayed state: kIStPreDecayResonantState 13
Hadron in the nucleus: kIStHadronInTheNucleus 14
Final state nuclear remnant: kIStFinalStateNuclearRemnant 15
Nucleon cluster target: kIStNucleonClusterTarget 16

 */

 /*
 
 ## Codes for start and end process (ignorar el 'code'

| Code | Process |
|---|---|
| 0 | `kG4primary` |
| 1 | `kG4CoupledTransportation` |
| 2 | `kG4FastScintillation` |
| 3 | `kG4Decay` |
| 4 | `kG4anti_neutronInelastic` |
| 5 | `kG4neutronInelastic` |
| 6 | `kG4anti_protonInelastic` |
| 7 | `kG4protonInelastic` |
| 8 | `kG4hadInelastic` |
| 9 | `kG4pipInelastic` |
| 10 | `kG4pimInelastic` |
| 11 | `kG4xipInelastic` |
| 12 | `kG4ximInelastic` |
| 13 | `kG4kaonpInelastic` |
| 14 | `kG4kaonmInelastic` |
| 15 | `kG4sigmapInelastic` |
| 16 | `kG4sigmamInelastic` |
| 17 | `kG4kaon0LInelastic` |
| 18 | `kG4kaon0SInelastic` |
| 19 | `kG4lambdaInelastic` |
| 20 | `kG4anti_lambdaInelastic` |
| 21 | `kG4He3Inelastic` |
| 22 | `kG4ionInelastic` |
| 23 | `kG4xi0Inelastic` |
| 24 | `kG4alphaInelastic` |
| 25 | `kG4tInelastic` |
| 26 | `kG4dInelastic` |
| 27 | `kG4anti_neutronElastic` |
| 28 | `kG4neutronElastic` |
| 29 | `kG4anti_protonElastic` |
| 30 | `kG4protonElastic` |
| 31 | `kG4hadElastic` |
| 32 | `kG4pipElastic` |
| 33 | `kG4pimElastic` |
| 34 | `kG4kaonpElastic` |
| 35 | `kG4kaonmElastic` |
| 36 | `kG4conv` |
| 37 | `kG4phot` |
| 38 | `kG4annihil` |
| 39 | `kG4nCapture` |
| 40 | `kG4nKiller` |
| 41 | `kG4muMinusCaptureAtRest` |
| 42 | `kG4muIoni` |
| 43 | `kG4eBrem` |
| 44 | `kG4CoulombScat` |
| 45 | `kG4hBertiniCaptureAtRest` |
| 46 | `kG4hFritiofCaptureAtRest` |
| 47 | `kG4photonNuclear` |
| 48 | `kG4muonNuclear` |
| 49 | `kG4electronNuclear` |
| 50 | `kG4positronNuclear` |
| 51 | `kG4compt` |
| 52 | `kG4eIoni` |
| 53 | `kG4muBrems` |
| 54 | `kG4hIoni` |
| 55 | `kG4muPairProd` |
| 56 | `kG4hPairProd` |
| 57 | `kG4LArVoxelReadoutScoringProcess` |
| 58 | `kG4ionIoni` |
| 59 | `kG4hBrems` |
| 60 | `kG4Transportation` |
| 61 | `kG4msc` |
| 62 | `kG4StepLimiter` |
| 63 | `kG4LegacyUNKNOWN` |
| 64 | `kG4RadioactiveDecayBase` |
| 1024 | `kG4UNKNOWN` |
 
 */